[server]
port = 8080
enableCORS = false
maxCacheSize = 2048
enableXsrfProtection=false
maxUploadSize = 200
runOnSave = true
enableStaticServing = true
enableWebsocketCompression = false

[browser]
serverPort = 8080

[logger]
level = "debug"
