[server]
port = 8501
enableCORS = false
maxCacheSize = 200
enableXsrfProtection=false
maxUploadSize = 200
runOnSave = true
enableStaticServing = true
enableWebsocketCompression = false

[browser]
serverPort = 8501

[logger]
level = "debug"
