[server]
port = 8501
enableCORS = false
maxCacheSize = 200
enableXsrfProtection=false
maxUploadSize = 200
runOnSave = true
enableStaticServing = true
enableWebsocketCompression = false
# If false, will attempt to open a browser window on start.
# Default: false unless (1) we are on a Linux box where DISPLAY is unset, or (2) server.liveSave is set.
headless = true
# Immediately share the app in such a way that enables live monitoring, and post-run analysis.
# Default: false
liveSave = false
# Automatically rerun script when the file is modified on disk.
# Default: false
runOnSave = false


[browser]
serverPort = 8501
# Internet address of the server that the browser should connect to. Can be IP address or DNS name.
# Default: 'localhost'
serverAddress = "0.0.0.0"
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = true

[logger]
level = "debug"

[global]
# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
# Default: true
showWarningOnDirectExecution = true
